sudo: required

services:
  - docker

before_install:
  - docker build -t idourah96/idourah-dockerhub/yellow_app -f ./services/web/Dockerfile.dev ./services/web

script:
  - docker run idourah96/idourah-dockerhub/yellow_app pytest

after_success:
  - docker build -t idourah96/idourah-dockerhub/yellow_page_nginx ./services/nginx
  - docker build -t idourah96/idourah-dockerhub/yellow_page_web ./services/web
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # push to dockerhub repository
  - docker push idourah96/idourah-dockerhub/yellow_page_nginx 
  - docker push idourah96/idourah-dockerhub/yellow_page_web
