sudo: required

services:
  - docker 

before_install:
  - docker build -t karatsuba96/yellow_app -f ./services/web/Dockerfile.dev ./services/web 

script:
  - docker run karatsuba96/yellow_app pytest