version: '3.9'
services:

  db:    
    image: postgres:alpine 
    env_file:
      - ./services/web/config/.env
    restart: always 
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  web:
    container_name: yellow_app
    build:
      context: ./services/web 
      dockerfile: Dockerfile.dev
    command: python manage.py run -h 0.0.0.0
    depends_on:
      - db 
    volumes:
      - ./services/web:/usr/src/app 
    ports:
      - 4000:4000
    env_file:
      - ./services/web/config/.env
    restart: always

volumes:
  postgres_data_dev: