version: '3.9'
services:
  db: 
    image: postgres:alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./services/web/config/.env.prod.db
    restart: always

  web: 
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:4000 manage:app 
    container_name: yellow_app
    restart: always
    volumes: 
      - ./services/web:/usr/src/app
    ports:
      - 4000:4000
    env_file:
      - ./services/web/config/.env.prod
    depends_on:
      - db
   
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  postgres_data: