"""created_at

Revision ID: 3de485813415
Revises: 53cde15be3d1
Create Date: 2022-06-17 07:55:29.739247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de485813415'
down_revision = '53cde15be3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_at')
    # ### end Alembic commands ###
