"""empty message

Revision ID: 47536bfe9148
Revises: 
Create Date: 2022-06-22 08:47:55.849581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47536bfe9148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
