"""_password property user data model

Revision ID: 53cde15be3d1
Revises: 319482f9a0f4
Create Date: 2022-06-17 04:54:22.848442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53cde15be3d1'
down_revision = '319482f9a0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.String(length=64), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
