FROM python:3.9.5-slim-buster

# set work directory
WORKDIR /usr/src/app/ 

ENV PYTHONDONTWRITEBYTECODE 1 
ENV PYTHONUNBEFFRED 1 

# install system dependencies
RUN apt-get update && apt-get install -y netcat

# install dependencies 
RUN pip install --upgrade pip
COPY requirements.txt /usr/src/app/ 
RUN pip install -r requirements.txt 

COPY . /usr/src/app/ 

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]