from decouple import config

SECRET_KEY = config('SECRET_KEY')
DEBUG = True
POSTGRES_PASSOWRD = config("POSTGRES_PASSWORD") 
POSTGRES_DB = config("POSTGRES_DB")
POSTGRES_USER = config("POSTGRES_USER")
TEST_DB = config("TEST_DB")

SQLALCHEMY_DATABASE_URI = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSOWRD}@:5432/{TEST_DB}?host=db"
SQLALCHEMY_TRACK_MODIFICATIONS = True 